# Generated by Django 4.1.1 on 2022-12-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_owner_name', models.CharField(max_length=50)),
                ('card_serial', models.CharField(max_length=4)),
                ('card_number', models.CharField(max_length=18)),
                ('card_date_create', models.DateTimeField(auto_now_add=True)),
                ('card_begin_active', models.DateTimeField()),
                ('card_end_active', models.DateTimeField()),
                ('card_status', models.CharField(max_length=10)),
            ],
        ),
    ]
