# Generated by Django 4.1.1 on 2022-12-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_card_balance_alter_card_card_begin_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('card_serial', models.CharField(blank=True, max_length=10, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_date_create_from', models.DateTimeField()),
                ('card_end_active', models.DateTimeField()),
                ('card_status', models.CharField(blank=True, choices=[('not_active', 'not_active'), ('active', 'active'), ('overdue', 'overdue')], max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='card_serial',
            field=models.CharField(max_length=10),
        ),
    ]
