# Generated by Django 4.1.1 on 2022-12-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardsearch_alter_card_card_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_op', models.CharField(choices=[('Add_sum', 'Add_sum'), ('Payment', 'Payment'), ('Transfer money', 'Transfer money')], max_length=20)),
                ('agent', models.CharField(default='', max_length=20)),
                ('contr_agent', models.CharField(max_length=20)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('summa', models.FloatField()),
                ('oper_info', models.TextField(blank=True)),
                ('checks', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ContrAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='card_serial',
            field=models.CharField(choices=[('AAB', 'AAB'), ('ACC', 'ACC'), ('CAB', 'CAB'), ('ABC', 'ABC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cardsearch',
            name='card_serial',
            field=models.CharField(blank=True, choices=[('AAB', 'AAB'), ('ACC', 'ACC'), ('CAB', 'CAB'), ('ABC', 'ABC')], max_length=10, null=True),
        ),
    ]
