# Generated by Django 4.1.1 on 2022-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_name_contragent_contr_agent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_gen_serial', models.CharField(choices=[('AAB', 'AAB'), ('ACC', 'ACC'), ('CAB', 'CAB'), ('ABC', 'ABC')], max_length=10)),
                ('card_gen_number', models.CharField(max_length=20)),
                ('card_gen_term_active', models.FloatField(choices=[('1', '1'), ('6', '6'), ('12', '12')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='cardoperation',
            name='contr_agent',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('D', 'D')], max_length=20),
        ),
    ]
